version: "2.1"
services:
  web:
    build: .
    volumes:
      - ./:/usr/src/app
    environment: 
      PORT: 3000
    ports:
      - "3000:3000"
    command: npm run dev
  mongo:
    image: mongo
    ports:
      - "27017:27017"